import { Project, CollaborationAd, ForumTopic, UserProfile } from '../types';

export const DEMO_USERS: UserProfile[] = [
  {
    uid: 'user_elara',
    email: 'elara@artishub.io',
    displayName: 'Elara Arts',
    handle: '@Elara_Arts',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    role: 'Digital Illustrator & Comic Creator',
    bio: 'Dessinatrice freelance & autrice de webcomics fantasy. Toujours à la recherche de scénaristes passionnés.',
    followersCount: 1420,
    likesCount: 5240,
  },
  {
    uid: 'user_rinzler',
    email: 'creator@artishub.io',
    displayName: 'J.K. Rinzler',
    handle: '@JK_Rinzler',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    role: 'Senior Concept Artist & Art Director',
    bio: 'Worldbuilder & Concept Artist cyberpunk. Focus sur les environnements sci-fi et le matte painting.',
    followersCount: 3890,
    likesCount: 12400,
  },
  {
    uid: 'user_chromarex',
    email: 'chromarex@artishub.io',
    displayName: 'ChromaRex',
    handle: '@ChromaRex',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    role: 'Lead Colorist & Lighting Artist',
    bio: 'Coloriste BD & Webtoon spécialisé en ambiances néon, contrastes vifs et atmosphères SF.',
    followersCount: 980,
    likesCount: 4120,
  },
  {
    uid: 'user_chen',
    email: 'alexchen@artishub.io',
    displayName: 'Alex Chen',
    handle: '@AlexChen3D',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    role: 'Hard Surface 3D Modeler',
    bio: 'Spécialiste Mecha & Props 3D sous Blender et ZBrush.',
    followersCount: 2100,
    likesCount: 8900,
  },
  {
    uid: 'user_nova_dev',
    email: 'nova@artishub.io',
    displayName: 'Nova Dev',
    handle: '@NovaDev',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    role: 'Full-stack Developer',
    bio: 'Développeur full-stack, passionné par les produits créatifs, les jeux et les expériences interactives.',
    followersCount: 760,
    likesCount: 2180,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Neon District Sector 7',
    description: 'Une mégalopole cyberpunk tentaculaire au coucher du soleil, où les néons holographiques percent la brume pluvieuse. Projet en cours pour un futur artbook narratif et série de BD animée.',
    author: 'J.K. Rinzler',
    authorUid: 'user_rinzler',
    authorHandle: '@JK_Rinzler',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    authorRole: 'Senior Concept Artist',
    imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1400&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80'
    ],
    category: 'Digital Art',
    tags: ['Cyberpunk', 'Environment', 'SciFi', 'Cityscape'],
    likes: 1240,
    likedBy: [],
    commentsCount: 342,
    status: 'En recherche de collaborateurs',
    createdAt: '2026-08-20',
    views: 8940,
    featured: true,
    comments: [
      {
        id: 'c1',
        authorUid: 'user_elara',
        authorName: 'Elara Arts',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Illustrator',
        content: 'Les reflets sur le bitume mouillé et la volumétrie violette sont tout simplement époustouflants ! Tu utilises Octane pour la base 3D ?',
        createdAt: 'Il y a 3 heures',
        likes: 24,
      },
      {
        id: 'c2',
        authorUid: 'user_chromarex',
        authorName: 'ChromaRex',
        authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Colorist',
        content: 'La palette magenta / cyan est parfaitement dosée sans saturer l\'œil. Bravo pour cette ambiance !',
        createdAt: 'Il y a 6 heures',
        likes: 18,
      }
    ]
  },
  {
    id: 'proj-2',
    title: 'Vanguard Mech Mk.IV',
    description: 'Modèle 3D haute précision d\'un exosquelette de combat lourd pour l\'exploration minière planétaire hostile. Rig complet et textures 4K PBR.',
    author: 'Alex Chen',
    authorUid: 'user_chen',
    authorHandle: '@AlexChen3D',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    authorRole: '3D Artist',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
    category: '3D Modeling',
    tags: ['Mecha', 'SciFi', 'Blender', 'HardSurface'],
    likes: 856,
    likedBy: [],
    commentsCount: 124,
    status: 'Terminé',
    createdAt: '2026-08-18',
    views: 4320,
    comments: [
      {
        id: 'c3',
        authorUid: 'user_rinzler',
        authorName: 'J.K. Rinzler',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Art Director',
        content: 'Le niveau de détail sur les articulations hydrauliques est monstrueux. Beau travail sur le baking normal map !',
        createdAt: 'Il y a 1 jour',
        likes: 9,
      }
    ]
  },
  {
    id: 'proj-3',
    title: 'Shadow Protocol - Ch. 4',
    description: 'Planche double issue du chapitre 4 de la BD manga cyberpunk Shadow Protocol. Combat intense à l\'encre noire traditionnelle rehaussée en numérique.',
    author: 'Studio Kuro',
    authorUid: 'user_elara',
    authorHandle: '@StudioKuro',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    authorRole: 'Manga Creator',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1000&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1000&q=80'
    ],
    category: 'BD & Manga',
    tags: ['Manga', 'Ink', 'Action', 'DarkFantasy'],
    likes: 3400,
    likedBy: [],
    commentsCount: 480,
    status: 'En cours',
    createdAt: '2026-08-21',
    views: 15600,
    comments: []
  },
  {
    id: 'proj-4',
    title: 'Whispering Ruins',
    description: 'Peinture numérique d\'une forêt ancienne engloutissant les vestiges d\'un temple magique. Rayons crépusculaires et flore bioluminescente.',
    author: 'Elena M.',
    authorUid: 'user_elara',
    authorHandle: '@Elena_M',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    authorRole: 'Concept Artist',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    category: 'Concept Art',
    tags: ['Fantasy', 'Ruins', 'Environment', 'Atmosphere'],
    likes: 2100,
    likedBy: [],
    commentsCount: 89,
    status: 'Terminé',
    createdAt: '2026-08-19',
    views: 7800,
    comments: []
  },
  {
    id: 'proj-5',
    title: 'Cosmic Wanderer: Storyboard Sequence',
    description: 'Découpage dynamique en 12 vignettes pour la scène d\'amerrissage d\'urgence sur Kepler-452b. Gestion du rythme et focales anamorphiques.',
    author: 'J.K. Rinzler',
    authorUid: 'user_rinzler',
    authorHandle: '@JK_Rinzler',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    authorRole: 'Storyboarder',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
    category: 'Storyboards',
    tags: ['Storyboard', 'Cinematic', 'SciFi'],
    likes: 920,
    likedBy: [],
    commentsCount: 45,
    status: 'En cours',
    createdAt: '2026-08-17',
    views: 3100,
    comments: []
  }
];

export const INITIAL_COLLABORATIONS: CollaborationAd[] = [
  {
    id: 'collab-1',
    title: 'Cherche Scénariste pour BD Fantasy',
    author: 'Elara Arts',
    authorUid: 'user_elara',
    authorHandle: '@Elara_Arts',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    roleNeeded: 'Writer / Scénariste',
    projectType: 'Comic / Manga',
    status: 'HIRING',
    description: 'I am a digital illustrator working on a dark fantasy graphic novel. I have the world-building and character designs ready, but I need an experienced writer to help structure the narrative arc and write compelling dialogue. Revenue share based on Kickstarter success.',
    tags: ['DarkFantasy', 'RevShare', 'Comic', 'GraphicNovel'],
    postedAgo: 'Posted 2h ago',
    createdAt: '2026-08-24T05:43:00Z',
    compensation: 'RevShare + Primes Kickstarter',
    contactEmail: 'elara@artishub.io',
    applications: []
  },
  {
    id: 'collab-2',
    title: 'Coloriste dispo pour projets SF & Webtoon',
    author: 'ChromaRex',
    authorUid: 'user_chromarex',
    authorHandle: '@ChromaRex',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    roleNeeded: 'Colorist',
    projectType: 'Comic / Manga',
    status: 'AVAILABLE',
    description: 'Available for freelance coloring work. Specialized in Sci-Fi and Cyberpunk aesthetics, heavy use of neon contrasts and atmospheric lighting. Rates are negotiable depending on page count. Fast turnaround time and professional communication.',
    tags: ['SciFi', 'Freelance', 'Webtoon', 'NeonAesthetics'],
    postedAgo: 'Posted 5h ago',
    createdAt: '2026-08-24T02:43:00Z',
    compensation: 'Freelance / Facturation à la page',
    contactEmail: 'chromarex@artishub.io',
    applications: []
  },
  {
    id: 'collab-3',
    title: 'Recherche Modélisateur 3D Mecha / Props',
    author: 'J.K. Rinzler',
    authorUid: 'user_rinzler',
    authorHandle: '@JK_Rinzler',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    roleNeeded: '3D Modeler',
    projectType: 'Video Game',
    status: 'HIRING',
    description: 'Pour un prototype de jeu vidéo indé Unreal Engine 5, nous recherchons un artiste 3D Hard Surface capable de modéliser des drones de patrouille et véhicules d\'exploration stylisés.',
    tags: ['UnrealEngine', 'IndieGame', 'HardSurface', 'Mecha'],
    postedAgo: 'Posted 1d ago',
    createdAt: '2026-08-23T11:20:00Z',
    compensation: 'Rémunéré / Contrat freelance',
    contactEmail: 'creator@artishub.io',
    applications: []
  },
  {
    id: 'collab-4',
    title: 'Illustrateur Cover & Character Design disponible',
    author: 'Alex Chen',
    authorUid: 'user_chen',
    authorHandle: '@AlexChen3D',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    roleNeeded: 'Illustrator',
    projectType: 'Commission',
    status: 'AVAILABLE',
    description: 'Disponible pour couvertures de romans fantasy/SF, fiches de personnages, et visuels promotionnels. Palette moderne et finitions poussées.',
    tags: ['CoverArt', 'CharacterDesign', 'Commission'],
    postedAgo: 'Posted 2d ago',
    createdAt: '2026-08-22T08:15:00Z',
    compensation: 'Sur devis',
    contactEmail: 'alexchen@artishub.io',
    applications: []
  }
];

export const INITIAL_FORUM_TOPICS: ForumTopic[] = [
  {
    id: 'topic-1',
    title: 'Mastering Procreate: Custom Brushes Workflow',
    author: 'ElenaRostov',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    category: 'tips',
    categoryLabel: 'Tips & Tutorials',
    subCategoryTag: 'Digital Art',
    tags: ['Procreate', 'Brushes', 'Tutorial'],
    repliesCount: 42,
    viewsCount: 2300,
    lastActivity: '2 hours ago',
    lastActivityUser: 'MarcusArt',
    createdAt: '2026-08-23',
    previewText: 'A comprehensive guide on creating dynamic grain and dual-color blend brushes in Procreate 5.3 to speed up concept illustration.',
    content: `Dans ce tutoriel complet, je vous montre pas à pas comment configurer des pinceaux personnalisés dans Procreate avec dynamique de pression, double texture et rendu texturé type peinture à l'huile traditionnelle.

### 1. Paramétrage de la forme de grain
Choisissez une texture 2048x2048 en niveau de gris sans raccord (seamless). Importez-la dans le menu Grain -> Éditer.

### 2. Dynamique de couleur & pression
Activez le jitter de teinte à 2% pour créer des micro-variations chromatiques vivantes qui imitent les pigments naturels.

Téléchargez le pack de 8 brosses gratuites partagé ci-dessous !`,
    replies: [
      {
        id: 'r1',
        author: 'MarcusArt',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Digital Painter',
        content: 'Merci infiniment pour ce partage ! Le paramétrage du jitter de teinte a complètement transformé mes rendus d\'ombres.',
        createdAt: 'Il y a 2 heures',
        likes: 12
      },
      {
        id: 'r2',
        author: 'ChromaRex',
        authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Colorist',
        content: 'Superbe astuce ! Est-ce que tu conseilles de baisser l\'opacité de base ou plutôt de jouer sur le flux ?',
        createdAt: 'Il y a 4 heures',
        likes: 5
      }
    ]
  },
  {
    id: 'topic-2',
    title: 'Blender 4.0 Geometry Nodes Complete Guide',
    author: 'NodeWizard',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    category: 'tips',
    categoryLabel: 'Tips & Tutorials',
    subCategoryTag: '3D Modeling',
    tags: ['Blender', 'GeometryNodes', 'Procedural'],
    repliesCount: 128,
    viewsCount: 6800,
    lastActivity: 'Yesterday',
    lastActivityUser: 'SarahC',
    createdAt: '2026-08-22',
    previewText: 'Everything you need to know about repeat zones, hair curves generation, and procedural building generation in Blender 4.0.',
    content: `Le système de Geometry Nodes dans Blender a franchi un cap majeur. Dans ce thread, nous explorons comment créer un générateur de villes procédurales avec façades aléatoires et enseignes néon automatiques.`,
    replies: [
      {
        id: 'r3',
        author: 'SarahC',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        authorRole: '3D Generalist',
        content: 'La boucle de Repeat Zone simplifie tellement la distribution des étages. Thread d\'utilité publique !',
        createdAt: 'Hier',
        likes: 22
      }
    ]
  },
  {
    id: 'topic-3',
    title: 'Color Theory: Achieving Cinematic Lighting',
    author: 'LightBender',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    category: 'tips',
    categoryLabel: 'Tips & Tutorials',
    subCategoryTag: 'Concept Art',
    tags: ['Lighting', 'ColorTheory', 'Cinematics'],
    repliesCount: 8,
    viewsCount: 950,
    lastActivity: '3 days ago',
    lastActivityUser: 'ArtNoob',
    createdAt: '2026-08-21',
    previewText: 'How to use warm key lights with cool ambient bounce to create depth and emotional resonance in digital paintings.',
    content: `L'éclairage cinématographique repose sur le contraste de température de couleur (Warm / Cool contrast). Voici 3 schémas d'éclairage infaillibles pour vos illustrations.`,
    replies: []
  },
  {
    id: 'topic-4',
    title: 'Cyberpunk Alleyway - Need feedback on composition',
    author: 'NeoTokyo',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    category: 'critiques',
    categoryLabel: 'Constructive Critiques',
    subCategoryTag: 'Composition',
    tags: ['Critique', 'Cyberpunk', 'Composition'],
    repliesCount: 15,
    viewsCount: 1200,
    lastActivity: '45 mins ago',
    lastActivityUser: 'CompositionGuru',
    createdAt: '2026-08-24',
    imagePreview: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
    previewText: 'Looking for advice on focal points and leading lines in my latest futuristic neon alley piece.',
    content: `Bonjour la commu ! Je bloque un peu sur le point focal principal. Est-ce que le personnage sous le parapluie se détache suffisamment par rapport aux enseignes lumineuses à l'arrière-plan ? Tous vos retours sont les bienvenus !`,
    replies: [
      {
        id: 'r4',
        author: 'CompositionGuru',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        authorRole: 'Senior Artist',
        content: 'Ton personnage manque un tout petit peu de contraste de valeur. Ajoute un rim light bleu cyan vif sur son épaule droite pour le découper du fond sombre !',
        createdAt: 'Il y a 45 minutes',
        likes: 14
      }
    ]
  },
  {
    id: 'topic-5',
    title: 'Fantasy Warrior Anatomy check',
    author: 'SketchMaster',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=300&q=80',
    category: 'critiques',
    categoryLabel: 'Constructive Critiques',
    subCategoryTag: 'Anatomy',
    tags: ['Anatomy', 'Sketch', 'Feedback'],
    repliesCount: 32,
    viewsCount: 2800,
    lastActivity: '5 hours ago',
    lastActivityUser: 'LineArtPro',
    createdAt: '2026-08-24',
    imagePreview: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    previewText: 'Checking dynamic pose foreshortening and torso muscles on a heavy armor warrior.',
    content: `Est-ce que le raccourci du bras gauche tenant la lance semble crédible ? J'ai l'impression que la perspective de l'avant-bras est trop tassée.`,
    replies: []
  },
  {
    id: 'topic-6',
    title: 'ZBrush 2024: New Dynamic Symmetry Tools Overview',
    author: 'ArtisHub Editorial',
    authorAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    category: 'news',
    categoryLabel: 'Industry News',
    subCategoryTag: 'Software Update',
    tags: ['ZBrush', 'Sculpting', 'IndustryNews'],
    repliesCount: 84,
    viewsCount: 12000,
    lastActivity: 'Oct 24, 2024',
    createdAt: '2024-10-24',
    previewText: 'Pixologic has just dropped the latest update featuring completely overhauled symmetry features that will change your sculpting workflow...',
    content: `Pixologic vient de déployer sa mise à jour majeure 2024 pour ZBrush, avec de nouveaux outils de symétrie dynamique radiale et locale, l'intégration améliorée du format USD et des pinceaux de déformation organique ultra-rapides.`,
    replies: []
  },
  {
    id: 'topic-7',
    title: 'LightBox Expo 2024 Recap: Top Panels & Announcements',
    author: 'ArtisHub Editorial',
    authorAvatar: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80',
    category: 'news',
    categoryLabel: 'Industry News',
    subCategoryTag: 'Event',
    tags: ['LightBoxExpo', 'Events', 'ConceptArt'],
    repliesCount: 215,
    viewsCount: 34000,
    lastActivity: 'Oct 22, 2024',
    createdAt: '2024-10-22',
    previewText: 'A comprehensive breakdown of the biggest concept art reveals, recruitment trends, and inspiring talks from this year\'s LightBox Expo in Pasadena...',
    content: `Retour sur l'édition 2024 de la LightBox Expo à Pasadena : les studios d'animation et de jeux vidéo ont partagé leurs retours d'expérience sur la production de séries d'animation et les nouvelles opportunités pour les créateurs indépendants.`,
    replies: []
  }
];
